// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
	KV_COLLECTIN: KVNamespace;
	JWT_SECRET: string;
}
