#:schema node_modules/wrangler/config-schema.json
name = "crud"
main = "src/index.tsx"
compatibility_date = "2024-10-04"
assets = { directory = "./public", binding = "ASSETS" }

[[kv_namespaces]]
binding = "KV_COLLECTIN"
id = "4901601e4caa4bb6857706426af81244"